from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector 

# revision identifiers, used by Alembic.
revision = '55a44200585f'
down_revision = 'd6bcde2b2eef'
branch_labels = None
depends_on = None


def upgrade():
    # Add registration_date with a default for existing rows
    op.add_column('students', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE students SET registration_date = NOW() WHERE registration_date IS NULL")
    op.alter_column('students', 'registration_date', nullable=False)

    # --- ADD THIS LINE ---
    # Set a default value for existing rows in the department column
    op.execute("UPDATE students SET department = 'General' WHERE department IS NULL")

    # This block can now run safely
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('face_embedding',
               existing_type=Vector(dim=256),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False) # This line will now succeed
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()')) # type: ignore

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()')) # type: ignore <-- FIX 2: Add this comment
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('face_embedding',
               existing_type=Vector(dim=256), # <-- FIX 1: Use Vector directly
               nullable=False)
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###