"""Update embedding dimension to 256 for OpenVINO

Revision ID: 5e0cf6335a0f
Revises: 3beb347d8ad8
Create Date: 2025-09-13 10:12:57.355186

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '5e0cf6335a0f'
down_revision = '3beb347d8ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               existing_nullable=True)

    # ### end Alembic commands ###
