"""Add role column to User model

Revision ID: d6bcde2b2eef
Revises: 5e0cf6335a0f
Create Date: 2025-09-16 16:48:10.325793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bcde2b2eef'
down_revision = '5e0cf6335a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        # Step 1: Add the column, but make it nullable for now
        batch_op.add_column(sa.Column('department', sa.String(length=120), nullable=True))

    # Step 2: Update existing rows with a default value
    op.execute("UPDATE students SET department = 'Unassigned' WHERE department IS NULL")

    # Step 3: Now that all rows have a value, alter the column to be NOT NULL
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('department', nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='teacher'))
        # To avoid the same error for the user table, we give a server_default
        # and then clean it up after.
        batch_op.alter_column('role', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('role')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
